manual.name=Vantagepoint_Analysis_Cubes_Installation_and_Configuration_Guide
booktitle=Vantagepoint Analysis Cubes Installation and Configuration Guide
spreadsheet.xml=ClassificationMap.xml
document.locale=enus
